/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary":                    "#036c48",
        "primary-dim":                "#005f3e",
        "primary-fixed":              "#9df5c6",
        "primary-fixed-dim":          "#90e6b9",
        "primary-container":          "#9df5c6",
        "on-primary":                 "#e1ffeb",
        "on-primary-container":       "#005e3e",
        "on-primary-fixed":           "#00492f",
        "on-primary-fixed-variant":   "#006946",
        "secondary":                  "#5d605d",
        "secondary-dim":              "#515451",
        "secondary-container":        "#e1e3df",
        "secondary-fixed":            "#e1e3df",
        "secondary-fixed-dim":        "#d3d5d1",
        "on-secondary":               "#f8f9f5",
        "on-secondary-container":     "#4f524f",
        "on-secondary-fixed":         "#3d403d",
        "on-secondary-fixed-variant": "#595c59",
        "tertiary":                   "#5a6341",
        "tertiary-dim":               "#4e5736",
        "tertiary-container":         "#eef8cd",
        "tertiary-fixed":             "#eef8cd",
        "tertiary-fixed-dim":         "#e0eabf",
        "on-tertiary":                "#f4fed2",
        "on-tertiary-container":      "#565f3e",
        "on-tertiary-fixed":          "#444d2d",
        "on-tertiary-fixed-variant":  "#616a48",
        "background":                 "#f9f9f8",
        "surface":                    "#f9f9f8",
        "surface-bright":             "#f9f9f8",
        "surface-dim":                "#d3dcd8",
        "surface-variant":            "#dde4e1",
        "surface-tint":               "#036c48",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f2f4f2",
        "surface-container":          "#ebefec",
        "surface-container-high":     "#e4e9e7",
        "surface-container-highest":  "#dde4e1",
        "on-surface":                 "#2d3432",
        "on-surface-variant":         "#5a615e",
        "on-background":              "#2d3432",
        "outline":                    "#757c7a",
        "outline-variant":            "#acb3b1",
        "inverse-surface":            "#0c0f0e",
        "inverse-primary":            "#9df5c6",
        "inverse-on-surface":         "#9c9d9c",
        "error":                      "#9f403d",
        "error-dim":                  "#4e0309",
        "error-container":            "#fe8983",
        "on-error":                   "#fff7f6",
        "on-error-container":         "#752121",
      },
      fontFamily: {
          headline: ["var(--font-manrope)", "sans-serif"],
          body:     ["var(--font-manrope)", "sans-serif"],
          label:    ["var(--font-manrope)", "sans-serif"],
      },  
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "0.75rem",
      },
    },
  },
  plugins: [],
};
